name: Build and Release Addon

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create addon folder
        run: |
          mkdir JacobsHodorRestyle
          rsync -av --exclude='.git' --exclude='.github' ./ JacobsHodorRestyle/

      - name: Create zip
        run: |
          zip -r JacobsHodorRestyle.zip JacobsHodorRestyle

      - name: Upload zip to release
        uses: softprops/action-gh-release@v1
        with:
          files: JacobsHodorRestyle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
